# NOTE: update this with your service name
service: pmb-plus-backend

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provder.region}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000
  environment: ${file(./env.yml):${self:custom.stage}, file(./env.yml):default}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
  #local
    db_local_user: ${file(./env.yml):local.db_local_user}
    db_local_database: ${file(env.yml):local.db_local_database}
    db_local_password: ${file(env.yml):local.db_local_password}
    db_port: 3306
    db_local_host: ${file(env.yml):local.db_local_host}
  #dev
    db_user_dev: ${file(env.yml):dev.db_user_dev}
    db_name_dev: ${file(env.yml):dev.db_name_dev}
    db_password_dev: ${file(env.yml):dev.db_password_dev}
    db_url_dev: ${file(env.yml):dev.db_url_dev}
  #prod
    db_user_prod: ${file(env.yml):prod.db_user_prod}
    db_name_prod: ${file(env.yml):prod.db_name_prod}
    db_password_prod: ${file(env.yml):prod.db_password_prod}
    db_url_prod: ${file(env.yml):prod.db_url_prod}
  vpc:
    securityGroupIds:
      - sg-0817d67e10564fcac
    subnetIds:
      - subnet-02caece9d0c09d9b3
      - subnet-0a5543550af69c4cb
      - subnet-0437b2c12ac33444f
      - subnet-043d6118efb6a6f9b
 

functions:
  graphql:
    handler: src/graphql.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post 
          cors: true 
          integration: lambda-proxy
          authorizer:
              arn:aws:cognito-idp:us-east-1:094935673706:userpool/us-east-1_Dm8Wvfq3Q
              arn:aws:cognito-idp:us-east-1:094935673706:userpool/us-east-1_o6CvWzyjU

      - http:
          path: graphql
          method: get 
          cors: true
          integration: lambda-proxy
          


resources:
  #Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  #S3
  - ${file(resources/s3-bucket.yml)}